#!/bin/bash

#cjpeg
cd mediabench2/cjpeg/
tar -xf jpegsrc.v6b.tar.gz
cd jpeg-6b/
make clean
chmod +x configure
./configure
make

cd ../../../

#djpeg
cd mediabench2/djpeg/
ln -s ../cjpeg/jpeg-6b/

cd ../../

#h263enc
cd mediabench2/h263enc/
tar -xf tmn-1.7.tar.gz
cd tmn-1.7/
make clean
make all

cd ../../../

#h263dec
cd mediabench2/h263dec/
ln -s ../h263enc/tmn-1.7/

cd ../../

#h264enc
cd mediabench2/h264enc/
unzip jm10.2.zip
cd JM/
sh unixprep.sh
cd lencod/
make

cd ../../../../

#h264dec
cd mediabench2/h264dec/
unzip jm10.2.zip
cd JM/
sh unixprep.sh
cd ldecod/
make

cd ../../../../

#jpg2000enc
cd mediabench2/jpg2000enc/
unzip jasper-1.701.0.zip
cd jasper-1.701.0/
chmod +x configure
./configure --build=powerpc
make

cd ../../../

#jpg2000dec
cd mediabench2/jpg2000dec/
ln -s ../jpg2000enc/jasper-1.701.0/

cd ../../

#mpeg2enc
cd mediabench2/mpeg2enc/
tar -xf mpeg2vidcodec_v12.tar.gz
cd mpeg2/
make

cd ../../../

#mpeg2dec
cd mediabench2/mpeg2dec/
ln -s ../mpeg2enc/mpeg2/

cd ../../

#mpeg4enc
sudo apt-get install -y libv4l-dev
sudo ln -s /usr/include/libv4l1-videodev.h   /usr/include/linux/videodev.h 
cd mediabench2/mpeg4enc/
tar -xf ffmpeg.2006_04_24.tgz
cd ffmpeg/
chmod +x configure
./configure --disable-strip
make

cd ../../../

#mpeg4dec
cd mediabench2/mpeg4dec/
ln -s ../mpeg4enc/ffmpeg/

#mediabench reports
make