#!/bin/bash

#adpcm
cd mediabench/adpcm/src/
make clean
make all

cd ../../../

#epic
cd mediabench/epic/src/
make clean
make all

cd ../../../

#g721
cd mediabench/g721/src/
make clean
make all

cd ../../../

#ghostscript
#cd mediabench/ghostscript/src/
#make clean
#make all

#cd ../../../

#gsm
#cd mediabench/gsm/
#make install

#cd ../../

#jpeg
cd mediabench/jpeg/jpeg-6a/
chmod +x configure
./configure
make clean
make all
cp -rf cjpeg djpeg jpegtran rdjpgcom wrjpgcom ../bin/

cd ../../../

#mesa
cd mediabench/mesa/
make clean
make linux
cd demos/
make clean
make linux

cd ../../../

#mpeg2

#pegwit

#pgp

#rasta